// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = StatsSlice | HeroVideoSlice;

type HomeDocumentDataSlices1Slice = HeroVideoSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
    /**
     * Slice Zone field in *Home*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
     * Meta Title field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: home.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: home.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Slice Zone field in *Home*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home.slices1[]
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices1: prismic.SliceZone<HomeDocumentDataSlices1Slice>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, 'home', Lang>;

interface NavigationDocumentData {}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, 'navigation', Lang>;

export type AllDocumentTypes = HomeDocument | NavigationDocument;

/**
 * Primary content in *HeroVideo → Default → Primary*
 */
export interface HeroVideoSliceDefaultPrimary {
    /**
     * Button field in *HeroVideo → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_video.default.primary.button
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button: prismic.KeyTextField;

    /**
     * Title field in *HeroVideo → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_video.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Subtitle field in *HeroVideo → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_video.default.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    subtitle: prismic.KeyTextField;

    /**
     * VideoURL field in *HeroVideo → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_video.default.primary.videourl
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    videourl: prismic.KeyTextField;
}

/**
 * Default variation for HeroVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroVideoSliceDefault = prismic.SharedSliceVariation<'default', Simplify<HeroVideoSliceDefaultPrimary>, never>;

/**
 * Slice variation for *HeroVideo*
 */
type HeroVideoSliceVariation = HeroVideoSliceDefault;

/**
 * HeroVideo Shared Slice
 *
 * - **API ID**: `hero_video`
 * - **Description**: HeroVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroVideoSlice = prismic.SharedSlice<'hero_video', HeroVideoSliceVariation>;

/**
 * Item in *Stats → Default → Primary → StatsGroup*
 */
export interface StatsSliceDefaultPrimaryStatenameItem {
    /**
     * Name field in *Stats → Default → Primary → StatsGroup*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: stats.default.primary.statename[].name
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    name: prismic.KeyTextField;

    /**
     * icon field in *Stats → Default → Primary → StatsGroup*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: stats.default.primary.statename[].icon
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    icon: prismic.ImageField<never>;

    /**
     * count field in *Stats → Default → Primary → StatsGroup*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: stats.default.primary.statename[].count
     * - **Documentation**: https://prismic.io/docs/field#number
     */
    count: prismic.NumberField;
}

/**
 * Primary content in *Stats → Default → Primary*
 */
export interface StatsSliceDefaultPrimary {
    /**
     * StatsGroup field in *Stats → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: stats.default.primary.statename[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    statename: prismic.GroupField<Simplify<StatsSliceDefaultPrimaryStatenameItem>>;
}

/**
 * Default variation for Stats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsSliceDefault = prismic.SharedSliceVariation<'default', Simplify<StatsSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Stats*
 */
type StatsSliceVariation = StatsSliceDefault;

/**
 * Stats Shared Slice
 *
 * - **API ID**: `stats`
 * - **Description**: Stats
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsSlice = prismic.SharedSlice<'stats', StatsSliceVariation>;

declare module '@prismicio/client' {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }

    interface CreateWriteClient {
        (repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
    }

    interface CreateMigration {
        (): prismic.Migration<AllDocumentTypes>;
    }

    namespace Content {
        export type {
            HomeDocument,
            HomeDocumentData,
            HomeDocumentDataSlicesSlice,
            HomeDocumentDataSlices1Slice,
            NavigationDocument,
            NavigationDocumentData,
            AllDocumentTypes,
            HeroVideoSlice,
            HeroVideoSliceDefaultPrimary,
            HeroVideoSliceVariation,
            HeroVideoSliceDefault,
            StatsSlice,
            StatsSliceDefaultPrimaryStatenameItem,
            StatsSliceDefaultPrimary,
            StatsSliceVariation,
            StatsSliceDefault,
        };
    }
}
