import { CssBaseline, ThemeProvider } from '@mui/material';
import theme from '../styles/theme';
import { Josefin_Sans } from 'next/font/google';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};
const josefin = Josefin_Sans({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <ThemeProvider theme={theme}>
                <CssBaseline />
                <body className={`${josefin.className}`}>{children}</body>
            </ThemeProvider>
        </html>
    );
}
