// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
    hero_video: dynamic(() => import('./HeroVideo')),
    stats: dynamic(() => import('./Stats')),
};
